### ISSUE TITLE
Auto update

### ISSUE THREAD

**Issue by aXGAZXa** [JonasBonno/docker-ftb-stoneblock-3#1]
Hi Jonas,

Thanks again for your awesome work, we have been using your images to run our small FTB servers for years.

In all that time I admit I have never really gotten any good at programming in Docker and use your images because they just tend to work out of the box! With this release you have provided update instructions but I do not know where to begin I'm afraid. In previous images you have set it up to always use the latest stable release and update automatically. Mau I ask is there a reason you have not implemented that in this instance? It is very helpful. We are planning to start a new Stoneblock server and are wishing to use 1.6.1.

Kind Regards

**Comment by JonasBonno** [comment]
Hi @aXGAZXa,

Thank you for reaching out to me, and I am glad to hear you enjoy the containers.

I simply forgot to setup my usual monitoring of new release for this mod-pack so I totally missed this new stable release.
Now corrected and setup for any future releases, and the new version is being built as I am writing on Docker Hub.
